### ISSUE TITLE
Allow setting assets per page via Settings.yaml

### ISSUE THREAD

**Issue by soee** [Flowpack/media-ui#85] opened 2021-08-02 11:55 UTC
At the moment number of asset we can se is hardcoded in `Resources/Private/JavaScript/core/src/constants/pagination.ts`
On large screens we can easily use/view more than 20 items.

It would be a good idea to have it configurable through Settings.yaml - single value or allow to define list of allowed values like 20,30,40,50,60 and based on this list, render dropdown next to switch mode button which will allow user to select how many items he want to see.

**Comment by Sebobo** [comment] 2021-08-03 07:54
Yes I agree, there is already a Todo in the code for that.

**Comment by Sebobo** [comment] 2022-12-22 09:48
Duplicate of #144

**Closed by Sebobo** 2022-12-22 09:48 UTC
Labels: Feature Request
