### ISSUE TITLE
Filter "Unused" shows documents which are still in use on pages

### ISSUE THREAD

**Issue by healthyplus-yves** [Flowpack/media-ui#158] opened 2022-12-01 12:03 UTC
Error: 
The filter "Unused" is set.
The view reloads, but documents are also displayed which are still in use on pages.

Expected behaviour:
Only documents that are not in use/available on pages are displayed.

**Comment by Sebobo** [comment] 2022-12-01 12:18
This is a bit hard to debug. I assume you use the AssetUsages package?

**Comment by healthyplus-yves** [comment] 2022-12-01 15:04
We do not currently use the "AssetUsages" package.
We had installed it once, but it had a lot of bugs and currently it still has open problems in the GitHub -> that's why we had uninstalled it back then.
Do we need the AssetUsages Package to work with the media-ui?

**Comment by Sebobo** [comment] 2022-12-01 15:35
The default usages calculation is part of the Neos Core and not part of this package.

If the usage is not correctly calculated it depends on how the documents are referenced.

Most usage strategies can only detect "references" in nodes and not inside editable text f.e..

The AssetUsages package only makes the calculation much faster which is necessary for larger installations.

Which issue in the AssetUsages do you mean? The one that doesn't update the usage when something is deleted with a reference?

**Comment by Sebobo** [comment] 2022-12-01 15:36
Either way this issue cannot be fixed in this package. When I know enough I can move it to the correct repository.

**Comment by healthyplus-yves** [comment] 2022-12-01 15:52
The documents are made available on pages via a download module so that Users can click on them, open them or download them.
However, some documents are displayed as unused despite active use as described above.

Regarding the asset usages, I would have to refer you to Peter Rauber, I don't know in detail which problems currently open in Github he sees as blockers.

**Comment by healthyplus-yves** [comment] 2022-12-01 15:52
Would it help if I showed you how the problem presents itself in our environment?

**Comment by Sebobo** [comment] 2022-12-02 12:01
It's probably best if Peter would show me the implementation details. Just from looking at the elements I will not be able to judge the issue.

**Comment by healthyplus-yves** [comment] 2022-12-02 13:38
Ok, i'll check with him and get back to you.

**Comment by healthyplus-yves** [comment] 2023-01-16 08:13
Just had a quick conversation with Peter and he will get in touch with you to check this issue.

**Comment by Sebobo** [comment] 2023-01-16 09:24
After discussing this with Peter the issue is that the filter is even shown even though proper results cannot be calculated without the `AssetUsage` package. I'll described the bug in #171

**Closed by Sebobo** 2023-01-16 09:24 UTC
Labels: Question
